# Redis Config
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

# Weather API Key
weather:
  api:
    key: ${WEATHER_API_KEY}
    url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/